name: NSChat
version: 4.54.5c
main: com.nighthawksurvival.chat.Chat
author: NoneVale
website: www.nighthawksurvival.com
depend: [Chitchat]
commands:
   chatgroup:
      aliases: [cg, chat]
permissions: